import { Entity, PrimaryColumn, Column, ValueTransformer } from 'typeorm';

const numericTransformer: ValueTransformer = {
  to: (v: number | null | undefined): number | null => (v == null ? null : v),
  from: (v: string | number | null): number | null =>
    v == null ? null : typeof v === 'number' ? v : parseFloat(v),
};

/**
 * Local dev DBs use SERIAL integer ids (auto-generated by the
 * `1779500000000-Categories` migration). The production DB on Render was
 * created with `id` as a UUID column, so the same row returns a UUID string.
 * We type the field as `string | number` and treat it as opaque text in the
 * Telegram callback layer so both schemas keep working without a destructive
 * migration.
 */
@Entity('categories')
export class Category {
  @PrimaryColumn()
  id!: number | string;

  @Column({ type: 'text', unique: true })
  name!: string;

  @Column({
    type: 'numeric',
    name: 'shipping_cost',
    nullable: true,
    precision: 10,
    scale: 2,
    transformer: numericTransformer,
  })
  shippingCost!: number | null;

  @Column({
    type: 'numeric',
    name: 'commission_etb',
    nullable: true,
    precision: 10,
    scale: 2,
    transformer: numericTransformer,
  })
  commissionEtb!: number | null;
}
